services:
  djangoapp:
    container_name: djangoapp
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./djangoApps:/djangoApps
      - ./data/web/static:/data/web/static/
      - ./data/web/media:/data/web/media/
    env_file:
      - ./dotenv_files/.env
    depends_on:
      - mysql

  mysql:
    container_name: mysql
    image: mysql:8.0
    volumes:
      - ./data/mysql/data:/var/lib/mysql
    env_file:
      - ./dotenv_files/.env
    ports:
      - "3306:3306"








      